version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ihm"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qb716vbnltqf"
s3_prefix = "ihm"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
